### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by HarvsG** [toby-p/rightmove_webscraper.py#18]
Running the below on a series of URLs each containing approx 1000 search results causes increasing memory usage until it crashes or freezes. It seems very strange for it to happen in python.

``` python
def scrape(searches):
    """ takes a dict 'urls' of  format {'search_name':'url'} of rightmove searches and combines
 them into one pandas dataframe"""
    df = pd.DataFrame(columns= ['price', 'type', 'address', 'url', 'agent_url', 
 'postcode', 'number_bedrooms', 'search_date','search'])

    for search in searches:
        rightmove_object = rightmove_data(searches[search])
        result_df = rightmove_object.get_results
        df = df.append(result_df, ignore_index=True)
        df = df.drop_duplicates().reset_index(drop=True)
        
    return df
```

I imagine it would take a lot of work to debug, but putting it here to help any future users.

**Comment by toby-p** [comment]
I don't know if this is pertinent to the bug or not, but this line looks wrong:

`rightmove_object = rightmove_data(urls[url])`

Since you are looping through the urls, shouldn't this just be:

`rightmove_object = rightmove_data(url)`

For reproducing the bug are you able to post a sample of the URLs you are using?

**Comment by HarvsG** [comment]
Its because of the changes I made for the sake of example. In this URLs is  dict in the format {search_name:url}, I'll edit my post to clarify

**Comment by toby-p** [comment]
Made some tweaks to the code in the new version so please upgrade and try again. If the issue occurs again please raise a new issue with a sample script with the details of the specific URLs being scraped.
