### ISSUE TITLE
Commercial property

### ISSUE THREAD

**Issue by ClaudeNovaMB** [toby-p/rightmove_webscraper.py#21]
Hi there,
This is a great package !
I have tried property type as commercial which doesnt work.
Any pointers?

**Comment by toby-p** [comment]
Thanks! Could you let me know if you get an error or just no results?

**Comment by ClaudeNovaMB** [comment]
An error. Invalid URL

Residential searches work perfectly

**Comment by toby-p** [comment]
Ok thanks - t bbe honest I never tried commercial searches before.  I think there's an assertion statement that raises that error, so it might just be a case of tweaking that, but will have to test if the xpaths are all the same for commercial results. Will look into it.

**Comment by ClaudeNovaMB** [comment]
Yeah, line 112 (function rent_or_sale) checks "https://www.rightmove.co.uk/**property-for-sale**/..."
Commercial url is slightly different "https://www.rightmove.co.uk/**commercial-property-for-sale**/...."

**Comment by ClaudeNovaMB** [comment]
xpath for price is still relevant

**Comment by ClaudeNovaMB** [comment]
Seem other xpaths look great too

**Comment by toby-p** [comment]
Cool, thanks. Feel free to submit a pull request if you think you have a fix.

**Comment by ClaudeNovaMB** [comment]
Let me know if you received the request and if your test result was a success.

**Comment by toby-p** [comment]
Apologies for the delay - have now implemented this functionality. Hope this helps!
