### ISSUE TITLE
Package not working on M1 processors becasue of Pandas 1.0.3 - can we bump?

### ISSUE THREAD

**Issue by matwasilewski** [toby-p/rightmove_webscraper.py#38]
Pandas 1.03 (indirectly through older numpy I think?) does not support M1 processors. To workaround this issue, I forked the repo, updated pandas to 1.3.5 and installed from wheel and everything seems to be fine; is there any reason for not updating pandas in the repo?

**Comment by toby-p** [comment]
Can't see a problem with that, will try it out later this week and upgrade if no problems.

**Comment by santiagonasar** [comment]
Thanks - just sending you a nudge about the issue. If you would need help with this / other things related to the repo maintenance I'm happy to help.
