### ISSUE TITLE
Keywords support

### ISSUE THREAD

**Issue by lkdmid** [toby-p/rightmove_webscraper.py#42]
I know there's no bandwidth for this project right now, so just an idea.

It'd be handy to be able to filter results by keywords, as supported by the website itself.

URL params example, using keywords "acre" and "acres": `&keywords=acre%2Cacres`

**Comment by toby-p** [comment]
You can pass any URL to init the scraper so this shouldn't need any additional work.

**Comment by lkdmid** [comment]
Perhaps I wasn't clear enough. By default, the keywords param doesn't work as on the RightMove website itself, keywords are simply used to preferentially order results, NOT return only matches.
